/**
 * (C) Copyright IBM Corporation 2015.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.ibm.websphere.samples.daytrader.web.prims;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import jakarta.inject.Inject;

import com.ibm.websphere.samples.daytrader.entities.QuoteDataBean;
import com.ibm.websphere.samples.daytrader.interfaces.TradeServices;
import com.ibm.websphere.samples.daytrader.util.Log;
import com.ibm.websphere.samples.daytrader.util.TradeConfig;

import jakarta.servlet.ServletConfig;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 *
 * PingJDBCReadPrepStmt uses a prepared statement for database read access. This
 * primative uses
 * {@link com.ibm.websphere.samples.daytrader.impl.direct.TradeDirect} to set
 * the
 * price of a random stock (generated by
 * {@link com.ibm.websphere.samples.daytrader.util.TradeConfig}) through the use
 * of prepared statements.
 *
 */


@WebServlet(name = "PingJDBCRead", urlPatterns = { "/servlet/PingJDBCRead" })
public class PingJDBCRead extends HttpServlet {

    TradeServices trade;

    @Inject
    @jakarta.enterprise.inject.Any
    jakarta.enterprise.inject.Instance<TradeServices> tradeServicesInstance;

    private static final long serialVersionUID = -8810390150632488526L;
    private static String initTime;
    private static int hitCount;

    public PingJDBCRead() {
        // Default constructor required for servlet container
    }

    /**
     * forwards post requests to the doGet method Creation date: (11/6/2000
     * 10:52:39 AM)
     *
     * @param res
     *             jakarta.servlet.http.HttpServletRequest
     * @param res2
     *             jakarta.servlet.http.HttpServletResponse
     */
    @Override
    public void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
        doGet(req, res);
    }

    /**
     * this is the main method of the servlet that will service all get
     * requests.
     *
     * @param request
     *                 HttpServletRequest
     * @param responce
     *                 HttpServletResponce
     **/
    @Override
    public void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
        res.setContentType("text/html");
        java.io.PrintWriter out = res.getWriter();
        String symbol = null;
        StringBuffer output = new StringBuffer(100);

        try {
            // TradeJDBC uses prepared statements so I am going to make use of
            // it's code.

            symbol = TradeConfig.rndSymbol();

            QuoteDataBean quoteData = null;
            int iter = TradeConfig.getPrimIterations();
            for (int ii = 0; ii < iter; ii++) {
                quoteData = trade.getQuote(symbol);
            }

            output.append("<html><head><title>Ping JDBC Read w/ Prepared Stmt.</title></head>"
                    + "<body><HR><FONT size=\"+2\" color=\"#000066\">Ping JDBC Read w/ Prep Stmt:</FONT><HR><FONT size=\"-1\" color=\"#000066\">Init time : "
                    + initTime);
            hitCount++;
            output.append("<BR>Hit Count: " + hitCount);
            if (quoteData != null) {
                output.append("<HR>Quote Information <BR><BR>: " + quoteData.toHTML());
            } else {
                output.append("<HR>No quote data available");
            }
            output.append("<HR></body></html>");
            out.println(output.toString());
        } catch (Exception e) {
            Log.error(e, "PingJDBCRead w/ Prep Stmt -- error getting quote for symbol", symbol);
            res.sendError(500, "PingJDBCRead Exception caught: " + e.toString());
        }

    }

    /**
     * returns a string of information about the servlet
     *
     * @return info String: contains info about the servlet
     **/
    @Override
    public String getServletInfo() {
        return "Basic JDBC Read using a prepared statment, makes use of TradeJDBC class";
    }

    /**
     * called when the class is loaded to initialize the servlet
     *
     * @param config
     *               ServletConfig:
     **/
    @Override
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
        hitCount = 0;
        initTime = new java.util.Date().toString();
        // Resolve the TradeServices implementation by configured runtime mode using CDI
        String key = TradeConfig.getRunTimeModeNames()[TradeConfig.getRunTimeMode()];
        for (TradeServices ts : tradeServicesInstance) {
            String beanName = getBeanName(ts);
            if (key.equals(beanName)) {
                this.trade = ts;
                break;
            }
        }
        if (this.trade == null) {
            List<String> available = new ArrayList<>();
            for (TradeServices ts : tradeServicesInstance) {
                available.add(getBeanName(ts));
            }
            throw new IllegalStateException("No TradeServices bean named '" + key + "' (available: " + available + ")");
        }
    }

    private String getBeanName(TradeServices ts) {
        // CDI proxy classes need getSuperclass() to find the actual class with annotations
        Class<?> clazz = ts.getClass();
        jakarta.inject.Named named = clazz.getAnnotation(jakarta.inject.Named.class);
        if (named == null && clazz.getSuperclass() != null) {
            named = clazz.getSuperclass().getAnnotation(jakarta.inject.Named.class);
        }
        if (named != null && !named.value().isEmpty()) {
            return named.value();
        }
        // Check superclass for qualifier annotations too
        Class<?> realClass = clazz;
        if (realClass.getSuperclass() != null && realClass.getSuperclass() != Object.class) {
            realClass = realClass.getSuperclass();
        }
        if (realClass.getAnnotation(com.ibm.websphere.samples.daytrader.interfaces.TradeJDBC.class) != null) {
            return "Direct (JDBC)";
        }
        if (realClass.getAnnotation(com.ibm.websphere.samples.daytrader.interfaces.TradeEJB.class) != null) {
            return "Full EJB3";
        }
        if (realClass.getAnnotation(com.ibm.websphere.samples.daytrader.interfaces.TradeSession2Direct.class) != null) {
            return "Session to Direct";
        }
        // Default to simple class name
        String simpleName = realClass.getSimpleName();
        return simpleName;
    }
}