/**
 * (C) Copyright IBM Corporation 2015, 2024.
 */
package com.ibm.websphere.samples.daytrader.startup;

import java.math.BigDecimal;

import jakarta.annotation.PostConstruct;
import jakarta.annotation.Resource;
import jakarta.ejb.Singleton;
import jakarta.ejb.Startup;
import jakarta.ejb.TransactionManagement;
import jakarta.ejb.TransactionManagementType;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.transaction.UserTransaction;

import org.eclipse.microprofile.config.inject.ConfigProperty;
import jakarta.inject.Inject;

import com.ibm.websphere.samples.daytrader.entities.AccountDataBean;
import com.ibm.websphere.samples.daytrader.entities.AccountProfileDataBean;
import com.ibm.websphere.samples.daytrader.entities.QuoteDataBean;
import com.ibm.websphere.samples.daytrader.util.Log;
import com.ibm.websphere.samples.daytrader.util.TradeConfig;

@Singleton
@Startup
@TransactionManagement(TransactionManagementType.BEAN)
public class DatabasePopulator {

    @PersistenceContext(unitName = "daytrader")
    EntityManager em;

    @Resource
    UserTransaction utx;

    @Inject
    @ConfigProperty(name = "trade.db.populate.on.startup", defaultValue = "true")
    boolean populateOnStartup;

    @Inject
    @ConfigProperty(name = "trade.max.users", defaultValue = "50")
    int maxUsers;

    @Inject
    @ConfigProperty(name = "trade.max.quotes", defaultValue = "100")
    int maxQuotes;

    @PostConstruct
    void onStart() {
        if (!populateOnStartup) {
            Log.log("Database population disabled via configuration");
            return;
        }

        // Create tables using JPA native queries (same connection pool as JPA)
        createTables();

        // Check if database already has data
        try {
            utx.begin();
            Number quoteCount = (Number) em.createNativeQuery("SELECT COUNT(*) FROM quoteejb").getSingleResult();
            utx.commit();
            if (quoteCount.longValue() > 0) {
                Log.log("Database already populated with " + quoteCount + " quotes. Skipping population.");
                return;
            }
        } catch (Exception e) {
            try { utx.rollback(); } catch (Exception re) { /* ignore */ }
            Log.log("Proceeding with database population...");
        }

        Log.log("TradeBuildDB: Populating DayTrader Database on startup...");

        try {
            utx.begin();
            populateQuotes();
            utx.commit();
            Log.log("TradeBuildDB: Quotes populated successfully");
        } catch (Exception e) {
            try { utx.rollback(); } catch (Exception re) { /* ignore */ }
            Log.error(e, "TradeBuildDB: Error populating quotes");
            return;
        }

        try {
            utx.begin();
            populateUsers();
            utx.commit();
            Log.log("TradeBuildDB: Users populated successfully");
        } catch (Exception e) {
            try { utx.rollback(); } catch (Exception re) { /* ignore */ }
            Log.error(e, "TradeBuildDB: Error populating users");
            return;
        }

        Log.log("TradeBuildDB: Database population complete!");
    }

    private void createTables() {
        Log.log("TradeBuildDB: Creating database tables via JPA native queries...");
        try {
            utx.begin();

            em.createNativeQuery("CREATE TABLE IF NOT EXISTS quoteejb ("
                + "SYMBOL VARCHAR(255) NOT NULL PRIMARY KEY, "
                + "COMPANYNAME VARCHAR(255), "
                + "VOLUME DOUBLE NOT NULL, "
                + "PRICE DECIMAL(14,2), "
                + "OPEN1 DECIMAL(14,2), "
                + "LOW DECIMAL(14,2), "
                + "HIGH DECIMAL(14,2), "
                + "CHANGE1 DOUBLE NOT NULL)").executeUpdate();

            em.createNativeQuery("CREATE TABLE IF NOT EXISTS accountprofileejb ("
                + "USERID VARCHAR(255) NOT NULL PRIMARY KEY, "
                + "PASSWD VARCHAR(255), "
                + "FULLNAME VARCHAR(255), "
                + "ADDRESS VARCHAR(255), "
                + "EMAIL VARCHAR(255), "
                + "CREDITCARD VARCHAR(255))").executeUpdate();

            em.createNativeQuery("CREATE TABLE IF NOT EXISTS accountejb ("
                + "ACCOUNTID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "LOGINCOUNT INTEGER NOT NULL, "
                + "LOGOUTCOUNT INTEGER NOT NULL, "
                + "LASTLOGIN TIMESTAMP, "
                + "CREATIONDATE TIMESTAMP, "
                + "BALANCE DECIMAL(14,2), "
                + "OPENBALANCE DECIMAL(14,2), "
                + "PROFILE_USERID VARCHAR(255), "
                + "CONSTRAINT FK_ACCT_PROFILE FOREIGN KEY (PROFILE_USERID) REFERENCES accountprofileejb(USERID))").executeUpdate();

            em.createNativeQuery("CREATE TABLE IF NOT EXISTS holdingejb ("
                + "HOLDINGID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "QUANTITY DOUBLE NOT NULL, "
                + "PURCHASEPRICE DECIMAL(14,2), "
                + "PURCHASEDATE TIMESTAMP, "
                + "ACCOUNT_ACCOUNTID INTEGER, "
                + "QUOTE_SYMBOL VARCHAR(255), "
                + "CONSTRAINT FK_HOLD_ACCT FOREIGN KEY (ACCOUNT_ACCOUNTID) REFERENCES accountejb(ACCOUNTID), "
                + "CONSTRAINT FK_HOLD_QUOTE FOREIGN KEY (QUOTE_SYMBOL) REFERENCES quoteejb(SYMBOL))").executeUpdate();

            em.createNativeQuery("CREATE TABLE IF NOT EXISTS orderejb ("
                + "ORDERID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "ORDERTYPE VARCHAR(255), "
                + "ORDERSTATUS VARCHAR(255), "
                + "OPENDATE TIMESTAMP, "
                + "COMPLETIONDATE TIMESTAMP, "
                + "QUANTITY DOUBLE NOT NULL, "
                + "PRICE DECIMAL(14,2), "
                + "ORDERFEE DECIMAL(14,2), "
                + "ACCOUNT_ACCOUNTID INTEGER, "
                + "QUOTE_SYMBOL VARCHAR(255), "
                + "HOLDING_HOLDINGID INTEGER, "
                + "CONSTRAINT FK_ORD_ACCT FOREIGN KEY (ACCOUNT_ACCOUNTID) REFERENCES accountejb(ACCOUNTID), "
                + "CONSTRAINT FK_ORD_QUOTE FOREIGN KEY (QUOTE_SYMBOL) REFERENCES quoteejb(SYMBOL), "
                + "CONSTRAINT FK_ORD_HOLD FOREIGN KEY (HOLDING_HOLDINGID) REFERENCES holdingejb(HOLDINGID))").executeUpdate();

            em.createNativeQuery("CREATE TABLE IF NOT EXISTS keygenejb ("
                + "KEYNAME VARCHAR(255) NOT NULL PRIMARY KEY, "
                + "KEYVAL INTEGER NOT NULL)").executeUpdate();

            utx.commit();
            Log.log("TradeBuildDB: Database tables created successfully");
        } catch (Exception e) {
            try { utx.rollback(); } catch (Exception re) { /* ignore */ }
            Log.error(e, "TradeBuildDB: Error creating tables");
        }
    }

    private void populateQuotes() {
        Log.log("TradeBuildDB: Creating " + maxQuotes + " Quotes...");
        for (int i = 0; i < maxQuotes; i++) {
            String symbol = "s:" + i;
            String companyName = "S" + i + " Incorporated";
            BigDecimal price = new BigDecimal(TradeConfig.rndPrice());

            QuoteDataBean quote = new QuoteDataBean();
            quote.setSymbol(symbol);
            quote.setCompanyName(companyName);
            quote.setPrice(price);
            quote.setOpen(price);
            quote.setLow(price);
            quote.setHigh(price);
            quote.setChange(0.0);
            quote.setVolume(0.0);
            em.persist(quote);
            if (i % 10 == 0) Log.log("Created quote: " + symbol);
        }
        em.flush();
    }

    private void populateUsers() {
        Log.log("TradeBuildDB: Registering " + maxUsers + " Users...");
        for (int i = 0; i < maxUsers; i++) {
            String userID = "uid:" + i;
            String fullname = TradeConfig.rndFullName();
            String email = TradeConfig.rndEmail(userID);
            String address = TradeConfig.rndAddress();
            String creditcard = TradeConfig.rndCreditCard();
            BigDecimal initialBalance = new BigDecimal((double)(TradeConfig.rndInt(100000)) + 200000);
            if (i == 0) initialBalance = new BigDecimal(1000000);

            AccountProfileDataBean profile = new AccountProfileDataBean();
            profile.setUserID(userID);
            profile.setPassword("xxx");
            profile.setFullName(fullname);
            profile.setAddress(address);
            profile.setEmail(email);
            profile.setCreditCard(creditcard);
            em.persist(profile);

            AccountDataBean account = new AccountDataBean();
            account.setProfile(profile);
            account.setCreationDate(new java.sql.Timestamp(System.currentTimeMillis()));
            account.setLastLogin(new java.sql.Timestamp(System.currentTimeMillis()));
            account.setBalance(initialBalance);
            account.setOpenBalance(initialBalance);
            account.setLoginCount(0);
            account.setLogoutCount(0);
            em.persist(account);
            if (i % 10 == 0) Log.log("Registered user: " + userID);
        }
        em.flush();
    }
}
